apiVersion: v1
kind: Secret
metadata:
  namespace: percona-backup
  name: percona-backup-secrets
type: Opaque
data:
  aws-access-key-id: BASE64_ENCODED_ACCESS_KEY_ID
  aws-secret-access-key: BASE64_ENCODED_SECRET_ACCESS_KEY
