apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard2
  namespace: mongodb-sharderd-cluster
  labels:
  role: shard2
  maintainer: vikas
spec:
  serviceName: shard2-service
  replicas: 3
  selector:
    matchLabels:
      role: shard2-replicas
  template:
    metadata:
      labels:
        role: shard2-replicas
    spec:
      containers:
        - name: shard2
          image: mongo:6.0
          volumeMounts:
            - name: shard2-data
              path: /data/db/
          ports:
            - containerPort: 27017
          commands:
            - mongod
            - "--shardsvr"
            - "--replSet=shard2Replicas"
            - "--bind_ip_all"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  role: shard2-replicas
              topologyKey: kubernetes.io/hostname
  volumeClaimTemplate:
    metadata:
      name: shard2-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "10Gi"
      storageClassName: "standard"

---
apiVersion: v1
kind: Service
metadata:
  name: shard2-service
  namespace: mongodb-sharderd-cluster
spec:
  clusterIP: None
  selector:
    role: shard2-replicas
  ports:
    - port: 27018
      protocol: TCP
      targetPort: 27018
