apiVersion: v1
kind: StatefulSet
metadata:
  name: shard1
  namespace: mongodb-sharderd-cluster
  labels:
    name: shard1
    maintainer: vikas
spec:
  serviceName: shard1-service
  replicas: 3
  selector:
    matchLabels:
      role: shard1-replicas
  template:
    metadata:
      name: shard1-pods
      labels:
        role: shard1-replicas
    spec:
      containers:
        - name: shard1-replicas-container
          image: mongo:6.0
          volumeMounts:
            - name: shard1-data
              path: /data/db
          ports:
            - containerPort: 27018
          command:
            - mongod
            - "--shardsvr"
            - "--replSet=shard1Replicas"
            - "--bind_ip_all"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  role: shard1-replicas
              topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    metadata:
      name: shard1-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "10Gi"
      storageClass: "standard"

---
apiVersion: v1
kind: Service
metadata:
  name: shard1-service
  namespace: mongodb-sharderd-cluster
spec:
  clusterIP: None
  selector:
    role: shard1-replicas
  ports:
    - port: 27018
      protocol: TCP
      targetPort: 27018
