apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos-deployment
  namespace: mongodb-sharderd-cluster
  labels:
    name: mongos
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mongos-query-router
  template:
    metadata:
      labels:
        name: mongos-query-router
    spec:
      containers:
        - name: mongos-query-router-container
          image: mongo:6.0
          command:
            - mongos
            - "--configDB=configReplicas/<dns>"
          ports:
            - containerPort: 27017
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  role: mongos-query-router
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: mongos-loadbalancer
  namespace: mongodb-sharderd-cluster
spec:
  type: LoadBalancer
  selector:
    name: mongos-query-router
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
