apiVersion: batch/v1
kind: CronJob
metadata:
  name: pbm-incremental-backup
spec:
  schedule: "0 3 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pbm-backup
              image: percona/percona-backup-mongodb:latest
              command:
                - /bin/sh
                - -c
                - |
                  pbm backup --type=incremental
              envFrom:
                - configMapRef:
                    name: percona-backup-configs
                - secretRef:
                    name: percona-backup-secrets
        restartPolicy: onFailure
